version: '3.8'
services:
  zookeeper1:
    container_name: zookeeper1
    image: wurstmeister/zookeeper
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/logs:/datalog"
    ports:
      - "12181:2181"

  zookeeper2:
    container_name: zookeeper2
    image: wurstmeister/zookeeper
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/logs:/datalog"
    ports:
      - "22181:2181"

  zookeeper3:
    container_name: zookeeper3
    image: wurstmeister/zookeeper
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/logs:/datalog"
    ports:
      - "32181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      # Topic 1 will have 1 partition and 1 replicas
      # 여러 Topic을 생성하고자 할 때는 쉼표로 구분하여 입력합니다. ex. "Topic1:1:1,Topic2:1:1"
      KAFKA_CREATE_TOPICS: "detection:1:1, emotion:1:1, drawing:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181, zookeeper2:2181, zookeeper3:2181
  
    # 볼륨 설정
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    # 의존 관계 설정
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3

