spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${HOST_PORT}/${MYSQL_DATABASE}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: Asia/Seoul

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379


server:
  flyway:
    enabled: false
  servlet:
    context-path: /api
logging:
  level:
    root: info

# constants
DOMAIN:
  FRONT: ${FRONT_DOMAIN} # localhost:5173
  BACK: ${BACK_DOMAIN} # http://localhost:8080
KAKAO:
  CLIENT_ID: ${KAKAO_OAUTH2_CLIENT_ID}
  REDIRECT_URI: ${BACK_DOMAIN}/api/auth/oauth2/kakao/callback
secretKeyPlain: ${SECURE_KEY_PLAIN} # 시큐리티 키

discord:
  webhook: ${DISCORD_WEBHOOK}
